version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file: .env   # ✅ 添加这一行，让 app 也能读取 .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/shardingdb?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456  # 现在能正确解析了
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=shardingdb
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  mysql_data: